// <auto-generated />
namespace EC_C2C_BanQuanAo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CapNhat_GioHang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CapNhat_GioHang));
        
        string IMigrationMetadata.Id
        {
            get { return "201712180536437_CapNhat_GioHang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
