// <auto-generated />
namespace EC_C2C_BanQuanAo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Doi_Length_Matkhau : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Doi_Length_Matkhau));
        
        string IMigrationMetadata.Id
        {
            get { return "201712051707318_Doi_Length_Matkhau"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
