// <auto-generated />
namespace EC_C2C_BanQuanAo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Them_TongTinConLai_TaiKhoan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Them_TongTinConLai_TaiKhoan));
        
        string IMigrationMetadata.Id
        {
            get { return "201712111534187_Them_TongTinConLai_TaiKhoan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
